- name: Disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Nodejs installation
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: copy backend file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: add user
  ansible.builtin.user:
    name: expense

- name: Extracting backend zip
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /app
    component: backend

- name: nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: mysql installation
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: load schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_HOST', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_USER', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_PASS', region='us-east-1' ) }} < /app/schema/backend.sql

- name: Restart backend
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Import ELK - filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat