- name: copy rsyslog to backend
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/{{ component }}.conf
  when: is_rsys_required

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  when: is_rsys_required

- name: copy elastic search repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name:  filebeat installation
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: copy filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

